server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
        # service 要与 tx-service-group 对齐，vgroupMapping 和 grouplist 在 service 的下一级，my_test_tx_group 在再下一级
        service:
          vgroupMapping:
            # 要和 tx-service-group 的值一致
            fsp_tx_group: default
          grouplist:
            # seata seaver 的 地址配置，此处可以集群配置是个数组
            default: 127.0.0.1:8091
    nacos:
      discovery:
        server-addr: 192.168.0.104:8848
        group: SEATA_GROUP
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.104:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://192.168.0.104:3306/seata_account
    username: root
    password: root

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml