server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinal-service
  cloud:
    nacos:
      discovery:
        # Nacos 服务注册中心地址（改成自己的服务器ip地址，本地用 localhost‍）
        server-addr: 192.168.0.102:8848
    sentinel:
      transport:
        # 配置 Sentinel dashboard 地址（改成自己的服务器 ip 地址，本地用 localhost‍）
        dashboard: 192.168.0.102:8858
        # 默认 8719 端口，假如被占用了会自动从 8719 端口 +1 进行扫描，直到找到未被占用的 端口
        port: 8719
      # 添加 Nacos 数据源配置
      datasource:
        ds1:
          nacos:
            # nacos
            server-addr: 192.168.0.102:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

# 激活 Sentinel 对 Feign 的支持
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'