server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      # 在此处配置要绑定的 rabbitmq 的服务信息
      binders:
        # 表示定义的名称，用于 binding 整合
        defaultRabbit:
          # 消息组件类型
          type: rabbit
          # 设置 rabbitmq 的相关环境配置
          environment:
            spring:
              rabbitmq:
                # RabbitMQ 在本机的用 localhost，在服务器的用服务器的ip地址
                host: 192.168.83.128
                port: 5672
                username: guest
                password: guest
      # 服务的整合处理
      bindings:
        # 这个名字是一个通道的名称 表示是消费者，这里是唯一和生产者不同的地方，向 rabbitMQ 发送消息
        input:
          # 表示要使用的 Exchange 名称定义
          destination: studyExchange
          # 设置消息类型，本次为 json，本文要设置为 “text/plain”
          content-type: application/json
          # 设置要绑定的消息服务的具体设置（爆红不影响使用，位置没错）
          binder: defaultRabbit
          # group: A

  rabbitmq:
    # RabbitMQ 在本机的用 localhost，在服务器的用服务器的ip地址
    host: 192.168.83.128
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    # 设置心跳的时间间隔（默认是 30S)
    lease-renewal-interval-in-seconds: 2
    # 如果超过 5S 间隔就注销节点 默认是 90s
    lease-expiration-duration-in-seconds: 5
    # 在信息列表时显示主机名称
    instance-id: receive-8802.com
    # 访问的路径变为 IP 地址
    prefer-ip-address: true