server:
  port: 80
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      # 用 linux 的 ip 地址（consul 在本机就填 localhost）
      host: 192.168.30.129
      port: 8500
      discovery:
        # 指定注册对外暴露的服务名称
        service-name: ${spring.application.name}